import {test,expect} from '@playwright/test';
async function scenePoint(page,x,y){return page.evaluate(async({x,y})=>{const T=await import('/vendor/three.module.js'),r=document.querySelector('.stage canvas').getBoundingClientRect(),h=208/(r.width/r.height),c=new T.OrthographicCamera(-104,104,h/2,-h/2,.1,600);c.position.set(54,38,160);c.lookAt(38,18,0);c.updateMatrixWorld();const p=new T.Vector3(x,y,4.3).project(c);return {x:r.left+(p.x*.5+.5)*r.width,y:r.top+(-p.y*.5+.5)*r.height};},{x,y});}
test('pointer drawing and erasing alter the solid barrier, taps place actors, hammer opens it',async({page})=>{await page.goto('/');const stage=page.locator('.stage');await expect(stage).toHaveAttribute('data-ready','true');
  await page.getByRole('button',{name:'Pencil',exact:true}).click();const crest=await scenePoint(page,38,23),higher=await scenePoint(page,38,34);await page.mouse.move(crest.x,crest.y);await page.mouse.down();await page.mouse.move(higher.x,higher.y,{steps:8});await page.mouse.up();await expect(stage).toHaveAttribute('data-dam-height','29.0');
  await page.getByRole('button',{name:'Eraser',exact:true}).click();await page.mouse.move(higher.x,higher.y);await page.mouse.down();await page.mouse.move(crest.x,crest.y,{steps:8});await page.mouse.up();await expect(stage).toHaveAttribute('data-dam-height','18.0');
  let people=Number(await stage.getAttribute('data-people')),boats=Number(await stage.getAttribute('data-boats'));
  for(const [name,x,y] of [['Person',58,3],['Rescuer',62,3],['Skiff',-26,5],['Rescue boat',-55,5]]){await page.getByRole('button',{name,exact:true}).click();const p=await scenePoint(page,x,y);await page.mouse.click(p.x,p.y);if(name==='Person'||name==='Rescuer')people++;else {boats++;people+=2;}await expect(stage).toHaveAttribute('data-people',String(people));await expect(stage).toHaveAttribute('data-boats',String(boats));}
  await page.getByRole('button',{name:'Start',exact:true}).click();await page.getByRole('button',{name:'Hammer',exact:true}).click();const dam=await scenePoint(page,38,18);for(let i=1;i<=5;i++){await page.mouse.click(dam.x,dam.y);await expect(page.locator('.dam-integrity')).toHaveText(`${100-i*20}%`);}await expect(stage).toHaveAttribute('data-breached','true');
  await page.getByRole('button',{name:'Shanghai',exact:true}).click();await expect(stage).toHaveAttribute('data-breached','false');await expect(stage).toHaveAttribute('data-people','30');await expect(stage).toHaveAttribute('data-boats','3');await expect(stage).toHaveAttribute('data-time','0.00');await expect(page.locator('.dam-integrity')).toHaveText('100%');});
test('named city selection, controls and finish restore a clean usable world',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'Tsunami Simulator'})).toBeVisible();await expect(page.locator('.stage')).toHaveAttribute('data-ready','true');for(const name of ['New York','Hawaii','Shanghai']){await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.stage')).toHaveAttribute('data-status','ready');await expect(page.locator('.dam-integrity')).toHaveText(/100%/);}await page.getByRole('button',{name:'Bigger',exact:true}).click();await expect(page.locator('.size-value')).toHaveText(/3/);await page.getByRole('button',{name:'Start',exact:true}).click();await expect(page.locator('.stage')).toHaveAttribute('data-status','running');await page.getByRole('button',{name:'Finish',exact:true}).click();await expect(page.locator('.stage')).toHaveAttribute('data-status','finished');const before=await page.locator('.stage').getAttribute('data-time');await page.waitForTimeout(800);expect(await page.locator('.stage').getAttribute('data-time')).toBe(before);await page.getByRole('button',{name:'Start',exact:true}).click();await expect(page.locator('.dam-integrity')).toHaveText(/100%/);expect(errors).toEqual([]);});
test('Pencil, Eraser, Hammer and entity selection have exclusive active state',async({page})=>{await page.goto('/');await expect(page.locator('.stage')).toHaveAttribute('data-ready','true');for(const tool of ['Pencil','Eraser']){await page.getByRole('button',{name:tool,exact:true}).click();await expect(page.getByRole('button',{name:tool,exact:true})).toHaveAttribute('aria-pressed','true');}await expect(page.getByRole('button',{name:'Pencil',exact:true})).toHaveAttribute('aria-pressed','false');await page.getByRole('button',{name:'Person',exact:true}).click();await expect(page.getByRole('button',{name:'Eraser',exact:true})).toHaveAttribute('aria-pressed','false');await page.getByRole('button',{name:'Start',exact:true}).click();await page.getByRole('button',{name:'Hammer',exact:true}).click();await expect(page.getByRole('button',{name:'Hammer',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'Person',exact:true})).toHaveAttribute('aria-pressed','false');});
test('phone controls and location names remain usable without horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');for(const name of ['Start','Finish','Smaller','Bigger','Shanghai','New York','Hawaii'])await expect(page.getByRole('button',{name,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();});
test.describe('touch input',()=>{test.use({hasTouch:true,viewport:{width:390,height:844}});test('one tap places one person and one hammer tap causes one hit',async({page})=>{await page.goto('/');await expect(page.locator('.stage')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Person',exact:true}).tap();const person=await scenePoint(page,58,3);await page.touchscreen.tap(person.x,person.y);await expect(page.locator('.stage')).toHaveAttribute('data-people','31');await page.getByRole('button',{name:'Start',exact:true}).tap();await page.getByRole('button',{name:'Hammer',exact:true}).tap();const dam=await scenePoint(page,38,18);await page.touchscreen.tap(dam.x,dam.y);await expect(page.locator('.dam-integrity')).toHaveText('80%');});});
