import * as T from '../../vendor/three.module.js';
import {loadMaterials,mat} from './materials.js';
import {createCityScene,disposeGeometry} from './CityScene.js';
import {createDam,createPerson,createBoat,createShip,createCar,createTree,createLight,createBin,box,mesh,sphere} from './models.js';
import {CALM_SEA,DAM_X,LAND_Y,hash} from '../simulation/locations.js';
export class Renderer {
  constructor(canvas,simulation){this.canvas=canvas;this.s=simulation;this.version=-1;this.entities=new Map();this.previewHeight=null;this.ray=new T.Raycaster();this.plane=new T.Plane(new T.Vector3(0,0,1),-4.3);this.point=new T.Vector3();
    this.reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;this.crackMaterial=new T.LineBasicMaterial({color:0x49463d});
    this.gpu=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.gpu.setPixelRatio(Math.min(devicePixelRatio,1.5));this.gpu.shadowMap.enabled=true;this.gpu.shadowMap.type=T.PCFSoftShadowMap;this.gpu.outputColorSpace=T.SRGBColorSpace;this.gpu.toneMapping=T.ACESFilmicToneMapping;this.gpu.toneMappingExposure=1.18;
    this.scene=new T.Scene();this.scene.background=new T.Color(simulation.location.sky);this.scene.fog=new T.Fog(simulation.location.sky,190,400);this.camera=new T.OrthographicCamera(-100,100,55,-55,.1,600);this.camera.position.set(54,38,160);this.camera.lookAt(38,18,0);
    this.scene.add(new T.HemisphereLight(0xd7ebf6,0xc1bca4,2.25));const sun=new T.DirectionalLight(0xfff0d8,3.2);sun.position.set(-35,95,75);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-130;sun.shadow.camera.right=160;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-70;sun.shadow.camera.far=300;sun.shadow.bias=-.0004;sun.shadow.normalBias=.15;this.scene.add(sun,sun.target);
    this.resize();this.build();
  }
  async load(){await loadMaterials();this.render();}
  thumbnails(){const result={};const target=new T.WebGLRenderTarget(180,110);const pixels=new Uint8Array(180*110*4),oldTarget=this.gpu.getRenderTarget();for(const kind of ['person','rescuer','skiff','cabin','fishing','rescue','rescue-launch']){const scene=new T.Scene();scene.background=new T.Color(0x1b3347);scene.add(new T.HemisphereLight(0xe5f1fa,0x899887,3));const light=new T.DirectionalLight(0xfff1d9,3);light.position.set(-5,8,10);scene.add(light);const g=kind==='person'||kind==='rescuer'?createPerson({color:0xd6d3c2,skin:0xc99a75,rescuer:kind==='rescuer'}):createBoat(kind);scene.add(g);const bounds=new T.Box3().setFromObject(g),center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3());const span=Math.max(size.y*1.15,size.x/1.6*1.1);const cam=new T.OrthographicCamera(-span*.82,span*.82,span*.5,-span*.5,.1,100);cam.position.copy(center).add(new T.Vector3(3,2,10));cam.lookAt(center);this.gpu.setRenderTarget(target);this.gpu.render(scene,cam);this.gpu.readRenderTargetPixels(target,0,0,180,110,pixels);const c=document.createElement('canvas');c.width=180;c.height=110;const ctx=c.getContext('2d'),data=ctx.createImageData(180,110);for(let y=0;y<110;y++)data.data.set(pixels.subarray((109-y)*720,(110-y)*720),y*720);ctx.putImageData(data,0,0);result[kind]=c.toDataURL('image/png');disposeGeometry(g);}target.dispose();this.gpu.setRenderTarget(oldTarget);this.render();return result;}
  resize(){const r=this.canvas.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);this.gpu.setSize(w,h,false);const aspect=w/h,worldWidth=208,worldHeight=worldWidth/aspect;this.camera.left=-worldWidth/2;this.camera.right=worldWidth/2;this.camera.top=worldHeight/2;this.camera.bottom=-worldHeight/2;this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();}
  build(){if(this.world){this.scene.remove(this.world);disposeGeometry(this.world);}this.entities.clear();this.previewHeight=null;const c=createCityScene(this.s);this.world=c.root;this.buildings=c.buildings;this.scene.add(this.world);this.scene.background.setHex(this.s.location.sky);this.scene.fog.color.setHex(this.s.location.sky);this.version=this.s.generation;this.damHeight=-1;this.makeDam();
    this.cracks=new T.Group();this.world.add(this.cracks);this.crackTier=-1;
    this.surface=createWater(this.s,false);this.front=createWater(this.s,true);this.world.add(this.surface,this.front);
    this.foam=new T.InstancedMesh(new T.SphereGeometry(.15,6,4),new T.MeshBasicMaterial({color:0xe0eef0,transparent:true,opacity:.8}),130);this.foam.instanceMatrix.setUsage(T.DynamicDrawUsage);this.foam.userData.ownedMaterial=true;this.world.add(this.foam);
    this.spray=new T.InstancedMesh(new T.SphereGeometry(.10,5,4),new T.MeshBasicMaterial({color:0xe1eeee}),260);this.spray.instanceMatrix.setUsage(T.DynamicDrawUsage);this.spray.userData.ownedMaterial=true;this.world.add(this.spray);this.spray.count=0;
  }
  makeDam(){if(this.dam){this.world.remove(this.dam);disposeGeometry(this.dam);}this.damHeight=this.previewHeight??this.s.dam.height;this.dam=createDam(this.damHeight);this.dam.position.set(DAM_X,CALM_SEA,0);this.world.add(this.dam);}
  showDamHeight(v){this.previewHeight=v;this.makeDam();this.render();}
  worldPoint(clientX,clientY){const r=this.canvas.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1),this.camera);this.ray.ray.intersectPlane(this.plane,this.point);return {x:this.point.x,y:this.point.y};}
  screenPoint(x,y,z=4.3){const p=new T.Vector3(x,y,z).project(this.camera),r=this.canvas.getBoundingClientRect();return {x:(p.x*.5+.5)*r.width,y:(-p.y*.5+.5)*r.height};}
  entity(id,create){if(!this.entities.has(id)){const g=create();this.entities.set(id,g);this.world.add(g);}return this.entities.get(id);}
  render(){const s=this.s;if(this.version!==s.generation)this.build();if(this.damHeight!==(this.previewHeight??s.dam.height))this.makeDam();
    if(s.dam.breached){const elapsed=s.time-s.dam.breachedAt;this.dam.userData.center.rotation.z=-Math.min(.9,elapsed*.23);this.dam.userData.center.position.set(Math.min(10,elapsed*2),-Math.min(11,elapsed*3),0);}else{this.dam.userData.center.rotation.z=0;this.dam.userData.center.position.set(0,0,0);}
    const tier=Math.floor((100-s.dam.integrity)/16);if(tier!==this.crackTier){this.crackTier=tier;disposeGeometry(this.cracks);this.cracks.clear();for(let i=0;i<tier;i++){const pts=[];const top=CALM_SEA+s.dam.height;for(let j=0;j<6;j++)pts.push(new T.Vector3(DAM_X-1.4+hash(j+i)*2.8,top-2-i*2-j*2,5.61));const line=new T.Line(new T.BufferGeometry().setFromPoints(pts),this.crackMaterial);this.cracks.add(line);}}
    this.cracks.visible=!s.dam.breached;
    for(const b of s.buildings){const g=this.buildings.get(b.id);g.position.y=b.y;g.rotation.z=-b.angle;for(const window of g.userData.windows){if(window.userData.lit){const flicker=b.light<1&&b.light>0?(Math.sin(s.time*18+b.x)>-.3?1:.2):1;window.material.color.setHex(b.light*flicker>.3?0xccac68:0x344b58);window.material.emissiveIntensity=.1*b.light*flicker;}}for(let i=0;i<g.userData.sections.length;i++){const section=g.userData.sections[i];if(b.damage>.75&&i>1){section.position.x=(i%2?.9:-.9)*(b.damage-.75)*i;section.rotation.z=(i%2?1:-1)*(b.damage-.75)*.35;}}}
    for(const b of s.boats){const g=this.entity(b.id,()=>createBoat(b.kind));g.position.set(b.x,b.y,5);g.rotation.z=b.angle;}
    for(const b of s.ships){const g=this.entity(b.id,createShip);g.position.set(b.x,b.y,-2);g.rotation.z=-b.angle;}
    for(const p of s.people){const g=this.entity(p.id,()=>createPerson(p));g.position.set(p.x,p.y,p.state==='aboard'?(s.ships.some(b=>b.id===p.boatId)?1.3:6.1):p.state==='roof'?2.9:6);g.rotation.z=p.angle;g.visible=p.x>-70&&p.x<150;
      const active=['street','climbing','swimming'].includes(p.state),stride=active?Math.sin(s.time*(p.state==='swimming'?4:9)+p.speed)*.6:0;g.userData.arms[0].rotation.z=p.state==='swimming'?1.4+stride:stride;g.userData.arms[1].rotation.z=p.state==='swimming'?-1.4-stride:-stride;g.userData.legs[0].rotation.z=stride*.7;g.userData.legs[1].rotation.z=-stride*.7;
    }
    for(const c of s.cars){const g=this.entity(c.id,()=>createCar(Number(c.id.split('-')[1]),c.color));g.position.set(c.x,c.y,5);g.rotation.z=c.angle;}
    for(const t of s.trees){const g=this.entity(t.id,()=>createTree(s.location.palm));g.position.set(t.x,t.y,1.7);g.rotation.z=-t.angle;}
    for(const l of s.lights){const g=this.entity(l.id,createLight);g.position.set(l.x,l.y,6.5);g.rotation.z=-l.angle;}
    for(const b of s.bins){const g=this.entity(b.id,createBin);g.position.set(b.x,b.y,6.8);g.rotation.z=b.angle;g.userData.lid.rotation.z=b.spilled?.8:0;}
    for(const t of s.trash){const g=this.entity(t.id,()=>{const g=new T.Group();box(g,.2,.08,.14,[0xd6c9a1,0xa9b7a3,0xbb9273][s.trash.indexOf(t)%3]);return g;});g.position.set(t.x,t.y,7);g.rotation.z=Math.sin(s.time+t.phase)*.3;}
    updateWater(this.surface,s,false);updateWater(this.front,s,true);
    const m=new T.Matrix4();let count=0;for(let i=0;i<130;i++){const x=-65+(i%65)*3.3,w=s.water.sample(x),z=i<65?8.2:-3;if(w.depth>.2&&(w.surface>6||x<DAM_X)){m.compose(new T.Vector3(x,w.surface+.07,z),new T.Quaternion(),new T.Vector3(1.4+Math.sin(s.time+x)*.3,.14,1.6));this.foam.setMatrixAt(count++,m);}}this.foam.count=count;this.foam.instanceMatrix.needsUpdate=true;
    this.spray.count=this.reducedMotion?Math.min(35,s.particles.length):s.particles.length;for(let i=0;i<this.spray.count;i++){const p=s.particles[i];m.makeTranslation(p.x,p.y,7+hash(i)*3);this.spray.setMatrixAt(i,m);}this.spray.instanceMatrix.needsUpdate=true;
    this.gpu.render(this.scene,this.camera);
  }
  dispose(){disposeGeometry(this.world);this.crackMaterial.dispose();this.gpu.dispose();}
}
function createWater(s,front){const positions=[],indices=[];const segments=220;for(let i=0;i<=segments;i++){const x=-70+i;for(let j=0;j<2;j++)positions.push(x,front?-25:5,front?9:(j===0?-13:9));}for(let i=0;i<segments;i++){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setIndex(indices);geo.computeVertexNormals();const material=front?new T.MeshBasicMaterial({color:s.location.water,transparent:true,opacity:.23,side:T.DoubleSide,depthWrite:false}):new T.MeshPhysicalMaterial({color:s.location.water,transparent:true,opacity:.58,roughness:.18,metalness:.22,side:T.DoubleSide,depthWrite:false,clearcoat:.6});const o=new T.Mesh(geo,material);o.renderOrder=front?3:2;o.userData.ownedMaterial=true;return o;}
function updateWater(o,s,front){const p=o.geometry.attributes.position;for(let i=0;i<=220;i++){const x=-70+i,w=s.water.sample(x),h=w.surface;for(let j=0;j<2;j++){const n=i*2+j;p.setY(n,front?(j===0?w.bed:h):h+(w.depth>.3?Math.sin(x*.65+s.time*2+(j?1:0))*.11:0));}}p.needsUpdate=true;if(!front)o.geometry.computeVertexNormals();}
